requires 'perl', '5.14.2';
requires 'Mojolicious', '4.75';
requires 'IO::Socket::IP', '0.20';
requires 'IO::Socket::SSL', '1.75';
requires 'EV', '4.0';
requires 'Data::Compare';
requires 'Hash::Merge';
requires 'List::MoreUtils';
requires 'DBIx::Connector';
requires 'DBD::mysql';
requires 'SQL::Abstract';
